import {rankCompanies} from '../market';
import {MOROCCO_CONFIG,MOROCCO_FX_USD_MAD,moroccoCompanies} from './morocco';
import {TUNISIA_CONFIG,TUNISIA_FX_USD_TND,tunisiaCompanies} from './tunisia';
import {ALGERIA_CONFIG,ALGERIA_FX_USD_DZD,algeriaCompanies} from './algeria';
import type {MarketCompany,MarketConfig,MarketDataProvider,MarketSummary} from './types';

export const EGYPT_CONFIG:MarketConfig={countryCode:'EG',countryName:'Egypt',flag:'🇪🇬',exchangeCode:'EGX',exchangeName:'Egyptian Exchange',currencyCode:'EGP',currencySymbol:'EGP',timezone:'Africa/Cairo',benchmark:'EGX 30',dataSource:'StockAnalysis EGX actively traded securities snapshot; market caps sourced directly',delay:'Delayed snapshot',lastUpdated:'2026-09-11T17:01:00+03:00'};
const egyptCompanies=():MarketCompany[]=>rankCompanies().map((c:any)=>({id:`EG-EGX-${c.ticker}`,countryCode:'EG',exchangeCode:'EGX',ticker:c.ticker,name:c.name,sector:c.industry,industry:c.industry,currency:'EGP',price:c.price,changePercent:c.changePercent,sharesOutstanding:c.sharesOutstanding,marketCapLocal:c.marketCapEGP,marketCapUSD:c.marketCapUSD,marketCapSource:'provider',timestamp:EGYPT_CONFIG.lastUpdated,dataSource:EGYPT_CONFIG.dataSource}));

function normalizeSnapshotShares(company:MarketCompany):MarketCompany{
  const shares=company.sharesOutstanding??(company.marketCapLocal!==undefined&&company.price!==undefined&&company.price>0?company.marketCapLocal/company.price:undefined);
  return {...company,sharesOutstanding:shares,marketCapSource:company.marketCapSource??(shares!==undefined?'calculated':undefined)};
}

const moroccoCompaniesSnapshot=()=>moroccoCompanies.map(c=>normalizeSnapshotShares({...c,marketCapUSD:c.marketCapLocal?c.marketCapLocal/MOROCCO_FX_USD_MAD:undefined}));
const tunisiaCompaniesSnapshot=()=>tunisiaCompanies.map(c=>normalizeSnapshotShares({...c,marketCapUSD:c.marketCapLocal?c.marketCapLocal/TUNISIA_FX_USD_TND:undefined}));
const algeriaCompaniesSnapshot=()=>algeriaCompanies.map(c=>normalizeSnapshotShares({...c,marketCapUSD:c.marketCapLocal?c.marketCapLocal/ALGERIA_FX_USD_DZD:undefined}));

const egyptProvider:MarketDataProvider={async getCompanies(){return egyptCompanies();},async getCompany(ticker){return egyptCompanies().find(c=>c.ticker.toUpperCase()===ticker.toUpperCase());},async getMarketSummary(){return summarize(egyptCompanies(),EGYPT_CONFIG,51.36,'Configured EGP/USD snapshot');},async getFX(){return 51.36;},async getMarketStatus(){return getMarketStatusSync('EG');}};
const moroccoProvider:MarketDataProvider={async getCompanies(){return moroccoCompaniesSnapshot();},async getCompany(ticker){return moroccoCompaniesSnapshot().find(c=>c.ticker.toUpperCase()===ticker.toUpperCase());},async getMarketSummary(){return summarize(moroccoCompaniesSnapshot(),MOROCCO_CONFIG,MOROCCO_FX_USD_MAD,'USD/MAD market snapshot');},async getFX(){return MOROCCO_FX_USD_MAD;},async getMarketStatus(){return getMarketStatusSync('MA');}};
const tunisiaProvider:MarketDataProvider={async getCompanies(){return tunisiaCompaniesSnapshot();},async getCompany(ticker){return tunisiaCompaniesSnapshot().find(c=>c.ticker.toUpperCase()===ticker.toUpperCase());},async getMarketSummary(){return summarize(tunisiaCompaniesSnapshot(),TUNISIA_CONFIG,TUNISIA_FX_USD_TND,'USD/TND market snapshot');},async getFX(){return TUNISIA_FX_USD_TND;},async getMarketStatus(){return getMarketStatusSync('TN');}};
const algeriaProvider:MarketDataProvider={async getCompanies(){return algeriaCompaniesSnapshot();},async getCompany(ticker){return algeriaCompaniesSnapshot().find(c=>c.ticker.toUpperCase()===ticker.toUpperCase());},async getMarketSummary(){return summarize(algeriaCompaniesSnapshot(),ALGERIA_CONFIG,ALGERIA_FX_USD_DZD,'USD/DZD market snapshot');},async getFX(){return ALGERIA_FX_USD_DZD;},async getMarketStatus(){return getMarketStatusSync('DZ');}};

function summarize(rows:MarketCompany[],config:MarketConfig,fxRate:number,fxSource:string):MarketSummary{return {count:rows.length,totalLocal:rows.reduce((s,c)=>s+(c.marketCapLocal??0),0),totalUSD:rows.reduce((s,c)=>s+(c.marketCapUSD??(c.marketCapLocal?c.marketCapLocal/fxRate:0)),0),industries:new Set(rows.map(c=>c.sector).filter(Boolean)).size,fxRate,fxSource,lastUpdated:rows.reduce((latest,row)=>row.timestamp&&row.timestamp>latest?row.timestamp:latest,config.lastUpdated),dataSource:config.dataSource,delay:config.delay};}

export const MARKET_REGISTRY:Record<string,{config:MarketConfig;provider:MarketDataProvider}>={EG:{config:EGYPT_CONFIG,provider:egyptProvider},MA:{config:MOROCCO_CONFIG,provider:moroccoProvider},TN:{config:TUNISIA_CONFIG,provider:tunisiaProvider},DZ:{config:ALGERIA_CONFIG,provider:algeriaProvider}};
export function getMarket(code:string){return MARKET_REGISTRY[code.toUpperCase()]??MARKET_REGISTRY.EG;}
export function hasMarket(code:string){return Boolean(MARKET_REGISTRY[code.toUpperCase()]);}
export function marketCodes(){return Object.keys(MARKET_REGISTRY);}
export function getMarketCompaniesSync(code:string){const normalized=code.toUpperCase();switch(normalized){case 'MA':return moroccoCompaniesSnapshot();case 'TN':return tunisiaCompaniesSnapshot();case 'DZ':return algeriaCompaniesSnapshot();default:return egyptCompanies();}}
export function getMarketCompanySync(code:string,ticker:string){return getMarketCompaniesSync(code).find(c=>c.ticker.toUpperCase()===ticker.toUpperCase());}
export function getMarketSummarySync(code:string){const normalized=code.toUpperCase();const market=getMarket(normalized);const fx=normalized==='MA'?MOROCCO_FX_USD_MAD:normalized==='TN'?TUNISIA_FX_USD_TND:normalized==='DZ'?ALGERIA_FX_USD_DZD:51.36;const source=normalized==='MA'?'USD/MAD market snapshot':normalized==='TN'?'USD/TND market snapshot':normalized==='DZ'?'USD/DZD market snapshot':`${market.config.currencyCode}/USD market snapshot`;return summarize(getMarketCompaniesSync(normalized),market.config,fx,source);}
export function getMarketStatusSync(code:string):'open'|'closed'|'auction'{const normalized=code.toUpperCase();const config=getMarket(normalized).config;const parts=new Intl.DateTimeFormat('en-US',{timeZone:config.timezone,weekday:'short',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date());const weekday=parts.find(p=>p.type==='weekday')?.value;const hour=Number(parts.find(p=>p.type==='hour')?.value??'0');const minute=Number(parts.find(p=>p.type==='minute')?.value??'0');const minutes=hour*60+minute;const weekend=normalized==='MA'||normalized==='TN'?weekday==='Sat'||weekday==='Sun':weekday==='Fri'||weekday==='Sat';const open=normalized==='MA'?570:normalized==='TN'?540:600;const close=normalized==='MA'?930:normalized==='TN'?900:900;return weekend?'closed':minutes>=open&&minutes<close?'open':'closed';}
export async function getMarketCompanies(code:string){return getMarket(code).provider.getCompanies();}
export async function getMarketCompany(code:string,ticker:string){return getMarket(code).provider.getCompany(ticker);}
export async function getMarketSummary(code:string){return getMarket(code).provider.getMarketSummary();}
export function rankMarketCompanies(companies:MarketCompany[]){return [...companies].sort((a,b)=>(b.marketCapLocal??-1)-(a.marketCapLocal??-1)).map((c,i)=>({...c,rank:c.marketCapLocal===undefined?undefined:i+1}));}
export function formatMarketCap(value:number|undefined,currency:string){if(value===undefined||value===null||!Number.isFinite(value))return '—';const prefix=currency==='USD'?'$':`${currency} `;if(Math.abs(value)>=1e12)return `${prefix}${(value/1e12).toFixed(2)}T`;if(Math.abs(value)>=1e9)return `${prefix}${(value/1e9).toFixed(2)}B`;if(Math.abs(value)>=1e6)return `${prefix}${(value/1e6).toFixed(0)}M`;return `${prefix}${Math.round(value).toLocaleString('en-US')}`;}
export function formatPrice(value:number|undefined,currency:string){if(value===undefined||value===null||!Number.isFinite(value))return '—';return `${currency} ${value.toLocaleString('en-US',{maximumFractionDigits:2})}`;}
