'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import CompanyIdentity from '@/components/company-identity';
import {MARKET_REGISTRY,formatMarketCap,formatPrice,getMarketStatusSync,rankMarketCompanies} from '@/lib/markets/registry';
import type {MarketCompany,MarketConfig} from '@/lib/markets/types';
import {NORTH_AFRICA_CODE} from '@/lib/markets/north-africa';

const TOP_LIMITS=[10,20,50,100,200,300,400,500,1000] as const;
const validLimit=(value:string|null)=>{const parsed=Number(value);return TOP_LIMITS.includes(parsed as (typeof TOP_LIMITS)[number])?parsed:100;};
const validCountry=(value:string|null)=>value?.toUpperCase()==='NA'||value&&MARKET_REGISTRY[value.toUpperCase()]?value!.toUpperCase():'EG';

type DisplayCompany=MarketCompany & {regionalRank?:number;countryName?:string;countryFlag?:string};

const NORTH_AFRICA_CONFIG:MarketConfig={countryCode:'NA',countryName:'North Africa',flag:'🌍',exchangeCode:'NA',exchangeName:'North Africa regional universe',currencyCode:'USD',currencySymbol:'$',timezone:'Africa/Cairo',benchmark:'Top 1,000 by USD market cap',dataSource:'Aggregated from Egypt, Morocco, Tunisia and Algeria market data',delay:'Inherited by underlying markets',lastUpdated:'2026-09-13T00:00:00Z'};

export default function HomeClient({initialCountry='EG',initialTop=100,initialSector='All',initialSearch='',initialExchange='All',initialRegionalCountry='All',initialCompanies=[]}:{initialCountry?:string;initialTop?:number;initialSector?:string;initialSearch?:string;initialExchange?:string;initialRegionalCountry?:string;initialCompanies?:DisplayCompany[]}){
  const [country,setCountry]=useState(()=>validCountry(initialCountry));
  const [companies,setCompanies]=useState<DisplayCompany[]>(initialCompanies);
  const [q,setQ]=useState(initialSearch);const [industry,setIndustry]=useState(initialSector);const [exchange,setExchange]=useState(initialExchange);const [regionalCountry,setRegionalCountry]=useState(initialRegionalCountry);const [limit,setLimit]=useState(initialTop);const [loading,setLoading]=useState(false);
  const isNorthAfrica=country===NORTH_AFRICA_CODE;
  useEffect(()=>{const onPop=()=>{const p=new URLSearchParams(window.location.search);const nextCountry=validCountry(p.get('country'));setCountry(nextCountry);setLimit(validLimit(p.get('top')));setIndustry(p.get('sector')??'All');setExchange(p.get('exchange')??'All');setRegionalCountry(p.get('regionalCountry')??'All');setQ(p.get('search')??'');};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
  useEffect(()=>{let cancelled=false;const controller=new AbortController();const load=async()=>{setLoading(true);try{const response=await fetch(`/api/markets/${country}/companies?limit=1000&regionalCountry=${encodeURIComponent(regionalCountry)}`,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error('Market data unavailable');const payload=await response.json() as {data?:DisplayCompany[]};if(!cancelled)setCompanies(payload.data??[]);}catch(error){if(!cancelled&&!(error instanceof DOMException&&error.name==='AbortError'))setCompanies([]);}finally{if(!cancelled)setLoading(false);}};load();return()=>{cancelled=true;controller.abort();};},[country,regionalCountry]);
  const market=MARKET_REGISTRY[country];const config=isNorthAfrica?NORTH_AFRICA_CONFIG:market?.config??MARKET_REGISTRY.EG.config;
  const allRows=useMemo<DisplayCompany[]>(()=>isNorthAfrica?[...companies].filter(c=>c.marketCapUSD!==undefined&&Number.isFinite(c.marketCapUSD)).sort((a,b)=>(b.marketCapUSD??-1)-(a.marketCapUSD??-1)).map((c,i)=>({...c,regionalRank:c.regionalRank??i+1})):rankMarketCompanies(companies),[companies,isNorthAfrica]);
  const summary=useMemo(()=>({count:allRows.length,totalLocal:allRows.reduce((s,c)=>s+(c.marketCapLocal??0),0),totalUSD:allRows.reduce((s,c)=>s+(c.marketCapUSD??0),0),industries:new Set(allRows.map(c=>c.sector).filter(Boolean)).size}),[allRows]);
  const status=isNorthAfrica?'closed':getMarketStatusSync(country);const industries=useMemo(()=>[...new Set(allRows.map(c=>c.sector).filter(Boolean) as string[])].sort(),[allRows]);const exchanges=useMemo(()=>isNorthAfrica?[]:config.exchanges??[{code:config.exchangeCode,name:config.exchangeName}],[config,isNorthAfrica]);
  const filtered=useMemo(()=>allRows.filter(c=>(isNorthAfrica?(regionalCountry==='All'||c.countryCode===regionalCountry):true)&&(exchange==='All'||c.exchangeCode===exchange)&&(industry==='All'||c.sector===industry)&&(`${c.name} ${c.ticker}`.toLowerCase().includes(q.trim().toLowerCase()))),[allRows,q,industry,exchange,isNorthAfrica,regionalCountry]);
  const rows=useMemo(()=>q.trim()?filtered:filtered.slice(0,limit),[filtered,q,limit]);
  const knownCaps=isNorthAfrica?allRows.filter(c=>c.marketCapUSD!==undefined).length:allRows.filter(c=>c.marketCapLocal!==undefined).length;
  const lastUpdated=useMemo(()=>allRows.map(c=>c.timestamp).filter(Boolean).sort().reverse()[0]??'—',[allRows]);
  function updateUrl(next:Partial<{country:string;limit:number;industry:string;q:string;exchange:string;regionalCountry:string}>){const params=new URLSearchParams(window.location.search);const nextCountry=next.country??country;const nextLimit=next.limit??limit;const nextIndustry=next.industry??industry;const nextExchange=next.exchange??exchange;const nextQ=next.q??q;const nextRegionalCountry=next.regionalCountry??regionalCountry;if(nextCountry==='EG')params.delete('country');else params.set('country',nextCountry);if(nextLimit===(nextCountry===NORTH_AFRICA_CODE?1000:100))params.delete('top');else params.set('top',String(nextLimit));if(nextIndustry==='All')params.delete('sector');else params.set('sector',nextIndustry);if(nextExchange==='All')params.delete('exchange');else params.set('exchange',nextExchange);if(nextRegionalCountry==='All')params.delete('regionalCountry');else params.set('regionalCountry',nextRegionalCountry);if(nextQ.trim())params.set('search',nextQ);else params.delete('search');window.history.pushState({},'',`${window.location.pathname}${params.toString()?`?${params}`:''}${window.location.hash}`);}
  function changeCountry(next:string){setCountry(next);setIndustry('All');setExchange('All');setRegionalCountry('All');setQ('');setLimit(next===NORTH_AFRICA_CODE?1000:100);updateUrl({country:next,industry:'All',exchange:'All',regionalCountry:'All',q:'',limit:next===NORTH_AFRICA_CODE?1000:100});}
  function changeLimit(next:number){setLimit(next);updateUrl({limit:next});}function changeIndustry(next:string){setIndustry(next);updateUrl({industry:next});}function changeExchange(next:string){setExchange(next);updateUrl({exchange:next});}function changeRegionalCountry(next:string){setRegionalCountry(next);updateUrl({regionalCountry:next});}function changeSearch(next:string){setQ(next);updateUrl({q:next});}
  const tableClass=isNorthAfrica?'table northAfricaTable':'table';
  return <><div className="shell"><header className="header"><div style={{display:'flex',flexDirection:'column',alignItems:'flex-start',justifyContent:'center',minWidth:0}}><Link href={`/markets?country=${country}`} className="brand"><strong>North Africa Hub</strong></Link><span style={{marginTop:3,color:'var(--muted)',fontSize:9,fontWeight:500,lineHeight:1.2,whiteSpace:'nowrap'}}>The United States of North Africa</span></div><nav className="nav"><Link href="#companies">Companies</Link><Link href={isNorthAfrica?'/industries':country==='EG'?'/industries':`/industries?country=${country}`}>Industries</Link><Link href="/methodology">About</Link></nav><div className="headerRight"><div className="status">{isNorthAfrica?'Regional universe':<><i className={`dot ${status==='open'?'positiveDot':''}`}/>{status==='open'?'Market open':'Market closed'}</>}</div></div></header>
  <main className="main"><section className="hero"><div><div className="eyebrow">{config.exchangeName}</div><div className="countryPicker"><label htmlFor="country">Market</label><select id="country" className="select countrySelect" value={country} onChange={e=>changeCountry(e.target.value)}><option value="NA">🌍 North Africa</option>{Object.entries(MARKET_REGISTRY).map(([code,m])=><option value={code} key={code}>{m.config.flag} {m.config.countryName}</option>)}</select></div><h1>{isNorthAfrica?<>North Africa's largest<br/>listed companies.</>:<>{config.countryName}'s largest<br/>listed companies.</>}</h1></div><div className="heroMeta">{loading?'Refreshing market data…':isNorthAfrica?'Regional universe · verified USD market caps':'Latest provider quote'}<br/><strong>{lastUpdated==='—'?'—':new Intl.DateTimeFormat('en-GB',{timeZone:config.timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(lastUpdated))} · {config.countryName}</strong><br/>{config.delay} · {config.dataSource}</div></section>
  <section className="summary"><div className="stat"><strong className="mono">{summary.count.toLocaleString('en-US')}</strong><span>{isNorthAfrica?'Companies in regional universe':'Companies available'}</span></div><div className="stat"><strong className="mono">{formatMarketCap(isNorthAfrica?summary.totalUSD:summary.totalLocal,config.currencyCode)}</strong><span>{isNorthAfrica?'Combined verified USD market cap':`Combined market cap · ${knownCaps}/${summary.count} with cap data`}</span></div><div className="stat"><strong className="mono">{formatMarketCap(summary.totalUSD,'USD')}</strong><span>{isNorthAfrica?'Regional comparison currency':'Combined USD value'}</span></div><div className="stat"><strong className="mono">{isNorthAfrica?'4':summary.industries}</strong><span>{isNorthAfrica?'Markets represented':'Sectors available'}</span></div></section>
  <section id="companies"><div className="toolbar"><div className="filters"><select aria-label="Ranking depth" className="select" value={limit} onChange={e=>changeLimit(+e.target.value)}>{TOP_LIMITS.map(n=><option key={n} value={n}>Top {n.toLocaleString()}</option>)}</select>{isNorthAfrica&&<select aria-label="Filter North Africa companies by country" className="select" value={regionalCountry} onChange={e=>changeRegionalCountry(e.target.value)}><option value="All">All countries</option><option value="EG">🇪🇬 Egypt</option><option value="MA">🇲🇦 Morocco</option><option value="TN">🇹🇳 Tunisia</option><option value="DZ">🇩🇿 Algeria</option></select>}{exchanges.length>1&&<select aria-label="Filter by exchange" className="select" value={exchange} onChange={e=>changeExchange(e.target.value)}><option value="All">All exchanges</option>{exchanges.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select>}<select aria-label="Filter by sector" className="select" value={industry} onChange={e=>changeIndustry(e.target.value)}><option>All</option>{industries.map(x=><option key={x}>{x}</option>)}</select></div><input aria-label="Search companies" className="search" placeholder={`Search ${isNorthAfrica?'North Africa':' '+config.countryName} companies…`} value={q} onChange={e=>changeSearch(e.target.value)}/></div>{!q&&limit>filtered.length&&<div className="searchNote">Showing all {filtered.length.toLocaleString('en-US')} available {isNorthAfrica?'North African':' '+config.countryName} listed companies. No placeholder rows are added.</div>}{q&&filtered.length>limit&&<div className="searchNote">Showing all matching companies across the full available {isNorthAfrica?'North African':' '+config.countryName} universe.</div>}
  <div className={tableClass}><div className="thead"><span>Rank</span><span>Company</span>{isNorthAfrica&&<span>Country</span>}<span>Ticker</span><span>Sector</span><span>Price</span><span>Change</span><span>Market cap</span></div>{rows.map(c=>{const companyMarket=c.countryCode||country;const displayRank=isNorthAfrica?(c.regionalRank??'—'):(c.rank??'—');return <Link href={`/company/${companyMarket}/${c.ticker}`} className="row" key={`${companyMarket}-${c.exchangeCode}-${c.ticker}`}><span className="rank mono">{typeof displayRank==='number'?String(displayRank).padStart(2,'0'):displayRank}</span><span><div className="company"><CompanyIdentity company={c}/></div><div className="sub">{c.ticker} · {c.exchangeCode} · {c.sector??'—'}</div><div className="mobileMarketCap"><b>{formatMarketCap(isNorthAfrica?c.marketCapUSD:c.marketCapLocal,isNorthAfrica?'USD':config.currencyCode)}</b><span>{isNorthAfrica?'':formatMarketCap(c.marketCapUSD,'USD')}</span></div></span>{isNorthAfrica&&<span className="value countryCell">{c.countryFlag} {c.countryName}</span>}<span className="value muted mono">{c.ticker}</span><span className="value muted">{c.sector??'—'}</span><span className="value mobilePrice mono">{formatPrice(c.price,isNorthAfrica?c.currency:config.currencyCode)}<span className={`mobileChange ${c.changePercent===undefined?'muted':c.changePercent>0?'positive':c.changePercent<0?'negative':'muted'}`}>{c.changePercent===undefined?'—':`${c.changePercent>0?'+':''}${c.changePercent.toFixed(2)}%`}</span></span><span className={`change mono ${c.changePercent===undefined?'muted':c.changePercent>0?'positive':c.changePercent<0?'negative':'muted'}`}>{c.changePercent===undefined?'—':`${c.changePercent>0?'+':''}${c.changePercent.toFixed(2)}%`}</span><span className="value desktopMarketCap mono"><b>{formatMarketCap(isNorthAfrica?c.marketCapUSD:c.marketCapLocal,isNorthAfrica?'USD':config.currencyCode)}</b>{!isNorthAfrica&&<div className="sub">{formatMarketCap(c.marketCapUSD,'USD')}</div>}</span></Link>;})}</div></section></main>
  <footer className="footer"><span>North Africa Hub</span><span>{isNorthAfrica?'Egypt · Morocco · Tunisia · Algeria':`${config.exchangeName} · ${config.currencyCode} · ${config.delay}`} · Updated {lastUpdated}</span></footer></div></>;
}
