'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import CompanyIdentity from '@/components/company-identity';
import {MARKET_REGISTRY,formatMarketCap,formatPrice,getMarketStatusSync,rankMarketCompanies} from '@/lib/markets/registry';
import type {MarketCompany} from '@/lib/markets/types';
import {NORTH_AFRICA_CONFIG,NORTH_AFRICA_COUNTRIES,getNorthAfricaStatus,isNorthAfrica} from '@/lib/markets/north-africa';

const TOP_LIMITS=[10,20,50,100,200,300,400,500,1000] as const;
const validLimit=(value:string|null)=>{const parsed=Number(value);return TOP_LIMITS.includes(parsed as (typeof TOP_LIMITS)[number])?parsed:100;};
const validCountry=(value:string|null)=>value&&((value.toUpperCase()==='NA')||MARKET_REGISTRY[value.toUpperCase()])?value.toUpperCase():'EG';
type RankedMarketCompany=MarketCompany & {rank?:number;regionalRank?:number};

export default function HomeClient({initialCountry='EG',initialTop=100,initialSector='All',initialSearch='',initialExchange='All',initialRegionalCountry='All',initialCompanies=[]}:{initialCountry?:string;initialTop?:number;initialSector?:string;initialSearch?:string;initialExchange?:string;initialRegionalCountry?:string;initialCompanies?:MarketCompany[]}){
  const [country,setCountry]=useState(()=>validCountry(initialCountry));
  const [companies,setCompanies]=useState<MarketCompany[]>(initialCompanies);
  const [q,setQ]=useState(initialSearch);const [industry,setIndustry]=useState(initialSector);const [exchange,setExchange]=useState(initialExchange);const [regionalCountry,setRegionalCountry]=useState(initialRegionalCountry);const [limit,setLimit]=useState(initialTop);const [loading,setLoading]=useState(false);const [refreshError,setRefreshError]=useState(false);
  const regional=isNorthAfrica(country);
  useEffect(()=>{const onPop=()=>{const p=new URLSearchParams(window.location.search);setCountry(validCountry(p.get('country')));setLimit(validLimit(p.get('top')));setIndustry(p.get('sector')??'All');setExchange(p.get('exchange')??'All');setRegionalCountry(p.get('marketCountry')??'All');setQ(p.get('search')??'');};window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
  useEffect(()=>{let cancelled=false;const controller=new AbortController();const load=async()=>{setLoading(true);setRefreshError(false);try{const params=new URLSearchParams({limit:'1000'});if(regionalCountry!=='All'&&regional)params.set('marketCountry',regionalCountry);const response=await fetch(`/api/markets/${country}/companies?${params.toString()}`,{signal:controller.signal,cache:'no-store'});if(!response.ok)throw new Error('Market data unavailable');const payload=await response.json() as {data?:MarketCompany[]};if(!cancelled){const nextCompanies=payload.data??[];if(nextCompanies.length>0||companies.length===0)setCompanies(nextCompanies);else setRefreshError(true);}}catch(error){if(!cancelled&&!(error instanceof DOMException&&error.name==='AbortError'))setRefreshError(true);}finally{if(!cancelled)setLoading(false);}};load();return()=>{cancelled=true;controller.abort();};},[country,regional,regionalCountry]);
  const config=regional?NORTH_AFRICA_CONFIG:(MARKET_REGISTRY[country]??MARKET_REGISTRY.EG).config;
  const marketRows=useMemo<RankedMarketCompany[]>(()=>regional?(companies as RankedMarketCompany[]):rankMarketCompanies(companies),[companies,regional]);
  const allRows=useMemo(()=>marketRows.filter(c=>regional?((c.marketCapUSD??0)>0):true),[marketRows,regional]);
  const summary=useMemo(()=>({count:allRows.length,totalLocal:regional?allRows.reduce((s,c)=>s+(c.marketCapUSD??0),0):allRows.reduce((s,c)=>s+(c.marketCapLocal??0),0),totalUSD:allRows.reduce((s,c)=>s+(c.marketCapUSD??0),0),industries:new Set(allRows.map(c=>c.sector).filter(Boolean)).size}),[allRows,regional]);
  const status=regional?getNorthAfricaStatus():getMarketStatusSync(country);
  const industries=useMemo(()=>[...new Set(allRows.map(c=>c.sector).filter(Boolean) as string[])].sort(),[allRows]);
  const exchanges=useMemo(()=>{if(regional)return [];const cfg=(MARKET_REGISTRY[country]??MARKET_REGISTRY.EG).config;return cfg.exchanges??[{code:cfg.exchangeCode,name:cfg.exchangeName}];},[country,regional]);
  const filtered=useMemo(()=>allRows.filter(c=>(regionalCountry==='All'||!regional||c.countryCode===regionalCountry)&&(exchange==='All'||c.exchangeCode===exchange)&&(industry==='All'||c.sector===industry)&&(`${c.name} ${c.ticker}`.toLowerCase().includes(q.trim().toLowerCase()))),[allRows,q,industry,exchange,regional,regionalCountry]);
  const rows=useMemo(()=>q.trim()?filtered:filtered.slice(0,limit),[filtered,q,limit]);
  const knownCaps=regional?allRows.length:allRows.filter(c=>c.marketCapLocal!==undefined).length;const lastUpdated=useMemo(()=>allRows.map(c=>c.timestamp).filter(Boolean).sort().reverse()[0]??'—',[allRows]);
  function updateUrl(next:Partial<{country:string;limit:number;industry:string;q:string;exchange:string;regionalCountry:string}>){const params=new URLSearchParams(window.location.search);const nextCountry=next.country??country;const nextLimit=next.limit??limit;const nextIndustry=next.industry??industry;const nextExchange=next.exchange??exchange;const nextRegionalCountry=next.regionalCountry??regionalCountry;const nextQ=next.q??q;if(nextCountry==='EG')params.delete('country');else params.set('country',nextCountry);if(nextLimit===100)params.delete('top');else params.set('top',String(nextLimit));if(nextIndustry==='All')params.delete('sector');else params.set('sector',nextIndustry);if(nextExchange==='All')params.delete('exchange');else params.set('exchange',nextExchange);if(nextRegionalCountry==='All'||nextCountry!=='NA')params.delete('marketCountry');else params.set('marketCountry',nextRegionalCountry);if(nextQ.trim())params.set('search',nextQ);else params.delete('search');window.history.pushState({},'',`${window.location.pathname}${params.toString()?`?${params}`:''}${window.location.hash}`);}
  function changeCountry(next:string){const nextLimit=next==='NA'?1000:100;setCountry(next);setIndustry('All');setExchange('All');setRegionalCountry('All');setQ('');setLimit(nextLimit);updateUrl({country:next,industry:'All',exchange:'All',regionalCountry:'All',q:'',limit:nextLimit});}function changeLimit(next:number){setLimit(next);updateUrl({limit:next});}function changeIndustry(next:string){setIndustry(next);updateUrl({industry:next});}function changeExchange(next:string){setExchange(next);updateUrl({exchange:next});}function changeRegionalCountry(next:string){setRegionalCountry(next);setQ('');setLimit(1000);updateUrl({regionalCountry:next,q:'',limit:1000});}function changeSearch(next:string){setQ(next);updateUrl({q:next});}
  const formatRowCap=(c:RankedMarketCompany)=>formatMarketCap(regional?c.marketCapUSD:c.marketCapLocal,regional?'USD':config.currencyCode);
  const rowRank=(c:RankedMarketCompany)=>regional?(c.regionalRank??'—'):(c.rank??'—');
  return <><div className="shell"><header className="header"><div style={{display:'flex',flexDirection:'column',alignItems:'flex-start',justifyContent:'center',minWidth:0}}><Link href={`/markets?country=${country}`} className="brand"><strong>North Africa Hub</strong></Link><span style={{marginTop:3,color:'var(--muted)',fontSize:9,fontWeight:500,lineHeight:1.2,whiteSpace:'nowrap'}}>The United States of North Africa</span></div><nav className="nav"><Link href="#companies">Companies</Link><Link href={country==='EG'?'/industries':`/industries?country=${country}`}>Industries</Link><Link href="/methodology">About</Link></nav><div className="headerRight"><div className="status"><i className={`dot ${status==='open'?'positiveDot':''}`}/>{status==='open'?'Market open':'Market closed'}</div></div></header>
  <main className="main"><section className="hero"><div><div className="eyebrow">{config.exchangeName}</div><div className="countryPicker"><label htmlFor="country">Market</label><select id="country" className="select countrySelect" value={country} onChange={e=>changeCountry(e.target.value)}><option value="NA">Regional · North Africa</option>{NORTH_AFRICA_COUNTRIES.map(code=><option value={code} key={code}>{MARKET_REGISTRY[code].config.flag} {MARKET_REGISTRY[code].config.countryName}</option>)}</select></div><h1>{regional?'North Africa’s largest':`${config.countryName}'s largest`}<br/>listed companies.</h1></div><div className="heroMeta">{loading?'Refreshing market data…':regional?'Regional market universe':'Latest provider quote'}<br/><strong>{lastUpdated==='—'?'—':new Intl.DateTimeFormat('en-GB',{timeZone:config.timezone,dateStyle:'medium',timeStyle:'short'}).format(new Date(lastUpdated))} · {regional?'Egypt · Morocco · Tunisia · Algeria':config.countryName}</strong><br/>{config.delay} · {config.dataSource}{refreshError&&<><br/><span style={{color:'var(--muted)'}}>Live refresh unavailable; showing the verified server snapshot.</span></>}</div></section>
  <section className="summary"><div className="stat"><strong className="mono">{summary.count}</strong><span>{regional?'Companies with verified USD market cap':'Companies available'}</span></div><div className="stat"><strong className="mono">{formatMarketCap(summary.totalLocal,regional?'USD':config.currencyCode)}</strong><span>{regional?'Combined verified USD market cap':`Combined market cap · ${knownCaps}/${summary.count} with cap data`}</span></div><div className="stat"><strong className="mono">{formatMarketCap(summary.totalUSD,'USD')}</strong><span>{regional?'Regional market value':'Combined USD value'}</span></div><div className="stat"><strong className="mono">{regional?'4':summary.industries}</strong><span>{regional?'Markets · Egypt · Morocco · Tunisia · Algeria':'Sectors available'}</span></div></section>
  <section id="companies"><div className="toolbar"><div className="filters"><select aria-label="Ranking depth" className="select" value={limit} onChange={e=>changeLimit(+e.target.value)}>{TOP_LIMITS.map(n=><option key={n} value={n}>Top {n.toLocaleString()}</option>)}</select>{regional&&<select aria-label="Filter North Africa by country" className="select" value={regionalCountry} onChange={e=>changeRegionalCountry(e.target.value)}><option value="All">All countries</option>{NORTH_AFRICA_COUNTRIES.map(code=><option key={code} value={code}>{MARKET_REGISTRY[code].config.flag} {MARKET_REGISTRY[code].config.countryName}</option>)}</select>}{exchanges.length>1&&<select aria-label="Filter by exchange" className="select" value={exchange} onChange={e=>changeExchange(e.target.value)}><option value="All">All exchanges</option>{exchanges.map(x=><option key={x.code} value={x.code}>{x.name}</option>)}</select>}<select aria-label="Filter by sector" className="select" value={industry} onChange={e=>changeIndustry(e.target.value)}><option>All</option>{industries.map(x=><option key={x}>{x}</option>)}</select></div><input aria-label="Search companies" className="search" placeholder={regional?'Search North Africa companies…':`Search ${config.countryName} companies…`} value={q} onChange={e=>changeSearch(e.target.value)}/></div>{!q&&limit>filtered.length&&<div className="searchNote">Showing all {filtered.length} available {regional?'North Africa':'listed'} companies. No placeholder rows are added.</div>}{regional&&<div className="searchNote">Regional rank is based on verified USD market capitalization. Country filters preserve the original North Africa rank.</div>}
  <div className={`table ${regional?'regionalTable':''}`}><div className="thead"><span>Rank</span><span>Company</span>{regional&&<span className="countryCell">Country</span>}<span>Ticker</span><span>Sector</span><span>Price</span><span>Change</span><span>Market cap</span></div>{rows.map(c=>{const rowCountry=c.countryCode;const rowConfig=MARKET_REGISTRY[rowCountry]?.config;return <Link href={`/company/${rowCountry}/${c.ticker}`} className="row" key={`${rowCountry}-${c.exchangeCode}-${c.ticker}`}><span className="rank mono">{rowRank(c)}</span><span><div className="company"><CompanyIdentity company={c}/></div><div className="sub">{c.ticker} · {c.exchangeCode} · {c.sector??'—'}{regional&&<span className="mobileRegionalCountry"> · {rowConfig?.flag} {rowConfig?.countryName}</span>}</div><div className="mobileMarketCap"><b>{formatRowCap(c)}</b>{regional?null:<span>{formatMarketCap(c.marketCapUSD,'USD')}</span>}</div></span>{regional&&<span className="value countryCell">{rowConfig?.flag} {rowConfig?.countryName??rowCountry}</span>}<span className="value muted mono">{c.ticker}</span><span className="value muted">{c.sector??'—'}</span><span className="value mobilePrice mono">{formatPrice(c.price,regional?'USD':config.currencyCode)}<span className={`mobileChange ${c.changePercent===undefined?'muted':c.changePercent>0?'positive':c.changePercent<0?'negative':'muted'}`}>{c.changePercent===undefined?'—':`${c.changePercent>0?'+':''}${c.changePercent.toFixed(2)}%`}</span></span><span className={`change mono ${c.changePercent===undefined?'muted':c.changePercent>0?'positive':c.changePercent<0?'negative':'muted'}`}>{c.changePercent===undefined?'—':`${c.changePercent>0?'+':''}${c.changePercent.toFixed(2)}%`}</span><span className="value desktopMarketCap mono"><b>{formatRowCap(c)}</b><div className="sub">{formatMarketCap(c.marketCapUSD,'USD')}</div></span></Link>})}</div></section></main>
  <footer className="footer"><span>North Africa Hub</span><span>{config.exchangeName} · {config.currencyCode} · {config.delay} · Updated {lastUpdated}</span><a href="https://www.allinvestview.com/tools/ticker-logos/">Logos by AllInvestView</a></footer></div><style jsx global>{`.regionalTable .thead,.regionalTable .row{grid-template-columns:60px minmax(240px,2fr) 125px 110px 130px 110px 120px 130px!important}.mobileRegionalCountry{display:none}.regionalTable .countryCell{display:block}@media(max-width:850px){.regionalTable .thead,.regionalTable .row{grid-template-columns:50px minmax(190px,1fr) 100px 110px 110px 110px 150px!important}}@media(max-width:600px){.row .rank{display:block!important;visibility:visible!important;color:var(--muted)!important;text-align:center}.row>span:nth-child(5){display:none!important}.row>span:nth-child(6){display:flex!important;flex-direction:column;align-items:flex-end;gap:4px;text-align:right;white-space:nowrap;align-self:start;padding-top:1px}.row>span:nth-child(6) .mobileChange{display:block}.regionalTable .row{grid-template-columns:26px minmax(0,1fr) minmax(74px,auto)!important}.regionalTable .row .countryCell{display:none}.regionalTable .mobileRegionalCountry{display:inline}.regionalTable .row>span:nth-child(3),.regionalTable .row>span:nth-child(4),.regionalTable .row>span:nth-child(5),.regionalTable .row>span:nth-child(7),.regionalTable .row>span:nth-child(8){display:none!important}}`}</style></>;
}
